services:
  java-maven-app:
    image: ${IMAGE}
    container_name: java-maven-app
    ports:
      - 8080:8080

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
